# Generated by Django 5.2.3 on 2025-06-14 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('secondary_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('suite', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DimEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('suite', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DimMovementReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.IntegerField()),
                ('referenced_from', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DimPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dimproduct',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='DimProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DimPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_date', models.DateField()),
                ('eta', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Arrived', 'Arrived'), ('Outgoing', 'Outgoing'), ('Canceled', 'Canceled')], default='Outgoing', max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='FactInventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movement_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimmovementreference')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimproduct')),
            ],
        ),
        migrations.CreateModel(
            name='FactInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('system_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Canceled', 'Canceled')], default='In Progress', max_length=20)),
                ('type', models.CharField(choices=[('Quote', 'Quote'), ('Invoice', 'Invoice')], default='Invoice', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimcustomer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimemployee')),
            ],
        ),
        migrations.CreateModel(
            name='FactInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('system_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.factinvoice')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimproduct')),
            ],
        ),
        migrations.CreateModel(
            name='FactPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimemployee')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.factinvoice')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimpaymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='FactPOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimpurchaseorder')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimproduct')),
            ],
        ),
        migrations.CreateModel(
            name='FactReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_date', models.DateField()),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.factinvoice')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimproduct')),
            ],
        ),
        migrations.CreateModel(
            name='FactShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Partially Complete', 'Partially Complete'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=30)),
                ('type', models.CharField(choices=[('Ship', 'Ship'), ('Pickup', 'Pickup')], max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.factinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='FactShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('stage_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Arrived', 'Arrived'), ('Outgoing', 'Outgoing'), ('Staged', 'Staged'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=30)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.factshipment')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dimproduct')),
            ],
        ),
    ]
